### ISSUE TITLE
Unable to resolve module `./util` from `node_modules\react-native-ytdl\lib\index.js`:

### ISSUE THREAD

**Issue by dungle27** [ytdl-js/react-native-ytdl#51] opened 2020-11-13 03:43 UTC
Hello
I try install latest version: 4.0.4
but occur this error: 
Unable to resolve module `./util` from `node_modules\react-native-ytdl\lib\index.js`:

please resolve help me
thank you so much!!

**Comment by AbelTesfaye** [comment] 2020-11-13 05:34
Duplicate of https://github.com/ytdl-js/react-native-ytdl/issues/47

**Comment by dungle27** [comment] 2020-11-20 10:31
@AbelTesfaye 
thank you!!!

**Closed** 2020-11-20 10:31 UTC
